const ICON_NAME_MAP = {
    erovnuli_angarishebi: 'erovnuli_angarishebi',
    national_accounts: 'erovnuli_angarishebi',
    economy: 'erovnuli_angarishebi',
    gdp: 'erovnuli_angarishebi',
    mosaxleoba_statistika: 'mosaxleoba_statistika',
    population: 'mosaxleoba_statistika',
    demographics: 'mosaxleoba_statistika',
    dasaqmeba_xelpasi: 'dasaqmeba_xelpasi',
    employment: 'dasaqmeba_xelpasi',
    labor: 'dasaqmeba_xelpasi',
    wages: 'dasaqmeba_xelpasi',
    fasebis_statistika: 'fasebis_statistika',
    prices: 'fasebis_statistika',
    inflation: 'fasebis_statistika',
    cpi: 'fasebis_statistika',
    sagareovachroba: 'sagareovachroba',
    trade: 'sagareovachroba',
    export: 'sagareovachroba',
    import: 'sagareovachroba',
    biznes_registri: 'biznes_registri',
    biznesSeqtori: 'biznesSeqtori',
    business: 'biznesSeqtori',
    enterprise: 'biznesSeqtori',
    mrewveloba_enerketika_msh: 'mrewveloba_enerketika_msh',
    industry: 'mrewveloba_enerketika_msh',
    construction: 'mrewveloba_enerketika_msh',
    energy: 'mrewveloba_enerketika_msh',
    soflis_meurneoba_sasursato_usap: 'soflis_meurneoba_sasursato_usap',
    agriculture: 'soflis_meurneoba_sasursato_usap',
    farming: 'soflis_meurneoba_sasursato_usap',
    turizmis_statistika: 'turizmis_statistika',
    tourism: 'turizmis_statistika',
    jadacva_socialuri_uzrunvelyopa: 'jadacva_socialuri_uzrunvelyopa',
    healthcare: 'jadacva_socialuri_uzrunvelyopa',
    health: 'jadacva_socialuri_uzrunvelyopa',
    social: 'jadacva_socialuri_uzrunvelyopa',
    cxovrebis_done: 'cxovrebis_done',
    living_standards: 'cxovrebis_done',
    poverty: 'cxovrebis_done',
    ganatleba_mecnier_sportI_kultura: 'ganatleba_mecnier_sportI_kultura',
    education: 'ganatleba_mecnier_sportI_kultura',
    garemosStatistika: 'garemosStatistika',
    environment: 'garemosStatistika',
    samartaldargvevisStatistika: 'samartaldargvevisStatistika',
    crime: 'samartaldargvevisStatistika',
    regionaluri_statistika: 'regionaluri_statistika',
    regions: 'regionaluri_statistika',
    momxsaxurebis_statistika: 'momxsaxurebis_statistika',
    services: 'momxsaxurebis_statistika',
    saxemlmwipo_finansebis_stat: 'saxemlmwipo_finansebis_stat',
    government_finance: 'saxemlmwipo_finansebis_stat',
    fiscal: 'saxemlmwipo_finansebis_stat',
    pirdapiri_ucxouri_invisticiebi: 'pirdapiri_ucxouri_invisticiebi',
    fdi: 'pirdapiri_ucxouri_invisticiebi',
    investment: 'pirdapiri_ucxouri_invisticiebi',
    sainpormacio_sakomunikacia: 'sainpormacio_sakomunikacia',
    ict: 'sainpormacio_sakomunikacia',
    mravalindekat_gamokvlelva: 'mravalindekat_gamokvlelva',
    surveys: 'mravalindekat_gamokvlelva',
    publication: 'publication',
    publications: 'publication',
    news: 'news',
    metadata: 'metadata',
    methodology: 'methodology',
    contact: 'contact',
    infographic: 'infographic',
    video: 'video',
    quest: 'quest',
    general: 'erovnuli_angarishebi',
    portal: 'erovnuli_angarishebi',
    stats: 'erovnuli_angarishebi',
    statistics: 'erovnuli_angarishebi',
};

export function getIconUrl(iconName) {
    if (!iconName) return null;
    const normalizedName = iconName.toLowerCase().replace(/[-\s]/g, '_');
    const mappedName = ICON_NAME_MAP[normalizedName] || ICON_NAME_MAP[iconName] || iconName;
    return `/icons/${mappedName}.svg`;
}
